name: ci

on:
  push:
  pull_request:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"              # caches `pip` downloads between runs

      - name: Install project (prod + dev)
        run: |
          python -m pip install --upgrade pip
          pip install -e ".[dev]"

      - name: Lint & Typecheck
        run: |
          ruff check .
          black --check .
          mypy .

      - name: Tests
        run: pytest -q
