name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      # Optional but helps some environments
      - name: Upgrade pip toolchain
        run: python -m pip install --upgrade pip wheel

      - name: Install uv
        run: python -m pip install uv

      # Ensure editable installs (PEP 660) work with Hatchling
      - name: Ensure recent hatchling
        run: python -m pip install --upgrade "hatchling>=1.24.0"

      # Install your project with dev extras so all tools (pytest, ruff, black, mypy, pre-commit) are available
      - name: Install project (prod + dev)
        run: uv pip install -e ".[dev]"

      # Run pre-commit hooks on all files
      - name: Run pre-commit
        run: uv run pre-commit run --all-files

      # Lint & typecheck inside the same environment
      - name: Lint & typecheck
        run: |
          uv run ruff check .
          uv run black --check .
          uv run mypy .

      # Run tests
      - name: Run tests
        run: uv run pytest --maxfail=1 --disable-warnings -q
