name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Upgrade pip toolchain
        run: python -m pip install --upgrade pip wheel

      - name: Install uv
        run: python -m pip install uv

      # ✅ Create an isolated venv for this workflow run
      - name: Create venv
        run: uv venv .venv

      # ✅ Install project (prod + dev) into that venv
      - name: Install project (prod + dev)
        run: uv pip install -e ".[dev]"

      # Pre-commit hooks
      - name: Run pre-commit
        run: uv run pre-commit run --all-files

      # Lint & typecheck
      - name: Lint & typecheck
        run: |
          uv run ruff check .
          uv run black --check .
          uv run mypy .

      # Run tests
      - name: Run tests
        run: uv run pytest --maxfail=1 --disable-warnings -q
